# Stage 1: Build the application
FROM maven:3.8.1-openjdk-17-slim AS build

WORKDIR /app

# Copy the pom.xml and src folder to the container
COPY pom.xml .
COPY src ./src

# Build the Spring Boot JAR file
RUN mvn clean package -DskipTests

# Stage 2: Create the final image
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/target/helloworld-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]

